version: '2.1'

services:
  cfpabot:
    restart: unless-stopped
    image: docker.cyan.cafe/cfpabot:latest
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./wwwroot:/app/userdata
      - ./Packer:/app/Packer
      - ./libgit2-e632535.so:/app/libgit2-e632535.so
      - ./project-hex:/app/project-hex
      - ./db:/app/db
#      - /data/cfpabot/repo-cache:/app/repo-cache # btrfs
    ports:
      - 19003:8080
    environment:
      - GITHUB_WEBHOOK_SECRET=
      - GITHUB_OAUTH_TOKEN=
     # - GITHUB_OAUTH_TOKEN=
     # - GITHUB_OAUTH_TOKEN=
      - CURSEFORGE_API_KEY=
      - CFPA_HELPER_GITHUB_OAUTH_CLIENT_SECRET=
      - EMAIL_PASSWORD=
      - CHATGPT_API_KEY=
      - HUOSHAN_API_KEY=
      - OPENROUTER_API_KEY=
      - OPENROUTER_API_KEY2=
      - GEMINI_API_KEY=
      - GEMINI_ENDPOINT=
      - DISABLE_PROJECT_HEX=
  wait:
    image: hello-world:latest
    depends_on:
      cfpabot:
          condition: service_healthy
