version: '2.1'

services:
  cfpabot:
    restart: unless-stopped
    build: ./CFPABot
    image: cfpabot:latest
    ports:
      - "19003:8080"
    volumes:
      - ./CFPABot/config:/app/config
      - ./CFPABot/runtime:/app/runtime
      - ./CFPABot/logs:/app/logs
    env_file:
      - ./CFPABot/.env
    environment:
      - TZ=Asia/Shanghai